using System;
using FruitFly.Living; // the HalfCentreOscillator circuit lives here; this file only DRAWS it
using Godot;

// Play 7 — Wingbeat CPG: a self-made rhythm (Plan 0007, rung 1 of the flight roadmap). PURE VIEWER
// (ADR 0005): the circuit — two neurons, mutual inhibition + fatigue — lives in
// FruitFly.Living.HalfCentreOscillator. This file builds NO neurons; it Steps the oscillator and
// draws it. (Same split as the Fly: brain in Living, drawing in Godot.)
//
// Rhythm is about TIME, so we draw a scrolling TIMELINE (newest at the right):
//   • L's firing fills UP from the centre line   (magenta)
//   • R's firing fills DOWN from the centre line  (cyan)
// The fill flips above/below the line as the cells take turns — that swing is the wingbeat. On the
// left sits a FLAT "drive" bar: steady input in, rhythmic output out — proof the timing is the
// brain's own, not handed to it.
public partial class WingbeatCpgView : Node2D
{
    private readonly HalfCentreOscillator _cpg = new();

    private const double StepMs = 1.0; // fixed stable Euler substep for the brain
    private const double SlowMotion = 0.6; // run a touch under real time so the swing is easy to watch
    private double _carryMs; // leftover sim time carried between frames, so tempo is frame-rate-independent

    // ---- Scrolling history (a ring buffer of the last few seconds) ----
    private const int HistLen = 320;
    private readonly float[] _histL = new float[HistLen];
    private readonly float[] _histR = new float[HistLen];
    private int _head;

    private Label _readout = null!;
    private int _handovers; // tally of turn-changes, just to show the beat is real
    private int _leader; // -1 = L ahead, +1 = R ahead, 0 = undecided

    public override void _Ready()
    {
        var title = new Label
        {
            Text =
                "Play 7 — Wingbeat CPG.  Two neurons take turns: magenta = LEFT, cyan = RIGHT.  "
                + "A steady drive (flat bar, left) goes in; a rhythmic beat comes out.  No timer.     (Esc = menu)",
            Position = new Vector2(24, 22),
        };
        title.AddThemeFontSizeOverride("font_size", 20);
        AddChild(title);

        _readout = new Label { Position = new Vector2(24, 56) };
        _readout.AddThemeFontSizeOverride("font_size", 18);
        AddChild(_readout);
    }

    public override void _UnhandledInput(InputEvent @event)
    {
        if (@event is InputEventKey { Pressed: true, Keycode: Key.Escape })
        {
            GetTree().ChangeSceneToFile("res://PlayMenu.tscn");
        }
    }

    public override void _Process(double delta)
    {
        // Advance the brain in fixed StepMs substeps (stable Euler), scaled by SlowMotion. Carry
        // the remainder so the beat keeps a steady wall-clock tempo whatever the frame length.
        _carryMs += delta * 1000.0 * SlowMotion;
        while (_carryMs >= StepMs)
        {
            _carryMs -= StepMs;
            _cpg.Step(StepMs); // the creature thinks; we just advance it
        }

        float l01 = (float)_cpg.LeftActivity;
        float r01 = (float)_cpg.RightActivity;

        _histL[_head] = l01;
        _histR[_head] = r01;
        _head = (_head + 1) % HistLen;

        // Count a handover when the lead flips, with a deadband so jitter doesn't flicker it.
        int now = r01 - l01 > 0.2f ? +1 : l01 - r01 > 0.2f ? -1 : _leader;
        if (now != _leader && _leader != 0)
        {
            _handovers++;
        }
        if (now != 0)
        {
            _leader = now;
        }

        string lead = _leader < 0 ? "LEFT" : _leader > 0 ? "RIGHT" : "—";
        _readout.Text =
            $"leading: {lead}    handovers: {_handovers}    (the rhythm is generated by the circuit, not a clock)";
        QueueRedraw();
    }

    // ---- Drawing: the scrolling timeline ----
    private const float StripX = 180f,
        StripY = 140f,
        StripW = 900f,
        StripH = 430f;

    public override void _Draw()
    {
        Font font = ThemeDB.FallbackFont;
        float cy = StripY + StripH * 0.5f; // the centre line = silence; fills grow away from it
        float halfH = StripH * 0.5f;

        DrawRect(new Rect2(StripX, StripY, StripW, StripH), new Color(1, 1, 1, 0.05f)); // backdrop

        // Steady-drive bar to the LEFT — deliberately FLAT, to contrast with the swinging output.
        DrawRect(new Rect2(StripX - 84f, cy - halfH * 0.5f, 32f, halfH), new Color(1, 1, 1, 0.18f));
        DrawString(font, new Vector2(StripX - 100f, cy + halfH * 0.5f + 26f), "steady drive",
            HorizontalAlignment.Left, -1, 16, new Color(1, 1, 1, 0.6f));

        float colW = StripW / HistLen;
        for (int i = 0; i < HistLen; i++)
        {
            int idx = (_head + i) % HistLen; // oldest on the left, newest on the right
            float x = StripX + i * colW;
            float lh = _histL[idx] * halfH;
            float rh = _histR[idx] * halfH;
            if (lh > 0f)
            {
                DrawRect(new Rect2(x, cy - lh, colW + 1f, lh), Colors.Magenta); // L grows UP
            }
            if (rh > 0f)
            {
                DrawRect(new Rect2(x, cy, colW + 1f, rh), new Color(0.2f, 0.85f, 1f)); // R grows DOWN
            }
        }

        DrawLine(new Vector2(StripX, cy), new Vector2(StripX + StripW, cy), new Color(1, 1, 1, 0.35f)); // centre
        float nowX = StripX + StripW;
        DrawLine(new Vector2(nowX, StripY), new Vector2(nowX, StripY + StripH), new Color(1, 1, 1, 0.4f)); // "now"

        DrawString(font, new Vector2(StripX + 10f, StripY + 24f), "LEFT wing",
            HorizontalAlignment.Left, -1, 20, new Color(1f, 0.5f, 1f, 0.85f));
        DrawString(font, new Vector2(StripX + 10f, StripY + StripH - 10f), "RIGHT wing",
            HorizontalAlignment.Left, -1, 20, new Color(0.4f, 0.9f, 1f, 0.9f));
    }
}
