using System;
using FruitFly.Living; // the HalfCentreOscillator circuit lives here; this file only DRAWS it
using Godot;

// Play 7 — Wingbeat CPG: a self-made rhythm (Plan 0007, rung 1 of the flight roadmap). PURE VIEWER
// (ADR 0005): the circuit — two neurons, mutual inhibition + fatigue — lives in
// FruitFly.Living.HalfCentreOscillator. This file builds NO neurons; it Steps the oscillator and
// draws it. (Same split as the Fly: brain in Living, drawing in Godot.)
//
// Rhythm is about TIME, so we draw a scrolling TIMELINE (newest at the right):
//   • L's firing fills UP from the centre line   (magenta)
//   • R's firing fills DOWN from the centre line  (cyan)
// The fill flips above/below the line as the cells take turns — that swing is the wingbeat. On the
// left sits a FLAT "drive" bar: steady input in, rhythmic output out — proof the timing is the
// brain's own, not handed to it.
public partial class WingbeatCpgView : Node2D
{
    private readonly HalfCentreOscillator _cpg = new();

    private const double StepMs = 1.0; // fixed stable Euler substep for the brain
    private const double SlowMotion = 0.6; // run a touch under real time so the swing is easy to watch
    private double _carryMs; // leftover sim time carried between frames, so tempo is frame-rate-independent

    // ---- Scrolling history (a ring buffer of the last few seconds) ----
    private const int HistLen = 320;
    private readonly float[] _histL = new float[HistLen];
    private readonly float[] _histR = new float[HistLen];
    private int _head;

    private Label _readout = null!;
    private int _handovers; // tally of turn-changes, just to show the beat is real
    private int _leader; // -1 = L ahead, +1 = R ahead, 0 = undecided

    public override void _Ready()
    {
        var title = new Label
        {
            Text =
                "Play 7 — Wingbeat CPG.  Two neurons take turns (downstroke vs upstroke) and that beat flaps the wings above.  "
                + "Both wings share ONE beat — they flap IN PHASE.  Steady drive in, rhythm out.  No timer.     (Esc = menu)",
            Position = new Vector2(24, 22),
        };
        title.AddThemeFontSizeOverride("font_size", 20);
        AddChild(title);

        _readout = new Label { Position = new Vector2(24, 56) };
        _readout.AddThemeFontSizeOverride("font_size", 18);
        AddChild(_readout);
    }

    public override void _UnhandledInput(InputEvent @event)
    {
        if (@event is InputEventKey { Pressed: true, Keycode: Key.Escape })
        {
            GetTree().ChangeSceneToFile("res://PlayMenu.tscn");
        }
    }

    public override void _Process(double delta)
    {
        // Advance the brain in fixed StepMs substeps (stable Euler), scaled by SlowMotion. Carry
        // the remainder so the beat keeps a steady wall-clock tempo whatever the frame length.
        _carryMs += delta * 1000.0 * SlowMotion;
        while (_carryMs >= StepMs)
        {
            _carryMs -= StepMs;
            _cpg.Step(StepMs); // the creature thinks; we just advance it
        }

        float l01 = (float)_cpg.LeftActivity;
        float r01 = (float)_cpg.RightActivity;

        _histL[_head] = l01;
        _histR[_head] = r01;
        _head = (_head + 1) % HistLen;

        // Count a handover when the lead flips, with a deadband so jitter doesn't flicker it.
        int now = r01 - l01 > 0.2f ? +1 : l01 - r01 > 0.2f ? -1 : _leader;
        if (now != _leader && _leader != 0)
        {
            _handovers++;
        }
        if (now != 0)
        {
            _leader = now;
        }

        string lead = _leader < 0 ? "LEFT" : _leader > 0 ? "RIGHT" : "—";
        _readout.Text =
            $"leading: {lead}    handovers: {_handovers}    (the rhythm is generated by the circuit, not a clock)";
        QueueRedraw();
    }

    // ---- Drawing: the scrolling timeline ----
    private const float StripX = 180f,
        StripY = 300f, // pushed down to leave room for the live flapping wings above
        StripW = 900f,
        StripH = 300f;

    public override void _Draw()
    {
        Font font = ThemeDB.FallbackFont;
        float cy = StripY + StripH * 0.5f; // the centre line = silence; fills grow away from it
        float halfH = StripH * 0.5f;

        DrawFlappingWings(font); // the live wingbeat the oscillator is driving, right now

        DrawRect(new Rect2(StripX, StripY, StripW, StripH), new Color(1, 1, 1, 0.05f)); // backdrop

        // Steady-drive bar to the LEFT — deliberately FLAT, to contrast with the swinging output.
        DrawRect(new Rect2(StripX - 84f, cy - halfH * 0.5f, 32f, halfH), new Color(1, 1, 1, 0.18f));
        DrawString(font, new Vector2(StripX - 100f, cy + halfH * 0.5f + 26f), "steady drive",
            HorizontalAlignment.Left, -1, 16, new Color(1, 1, 1, 0.6f));

        float colW = StripW / HistLen;
        for (int i = 0; i < HistLen; i++)
        {
            int idx = (_head + i) % HistLen; // oldest on the left, newest on the right
            float x = StripX + i * colW;
            float lh = _histL[idx] * halfH;
            float rh = _histR[idx] * halfH;
            if (lh > 0f)
            {
                DrawRect(new Rect2(x, cy - lh, colW + 1f, lh), Colors.Magenta); // L grows UP
            }
            if (rh > 0f)
            {
                DrawRect(new Rect2(x, cy, colW + 1f, rh), new Color(0.2f, 0.85f, 1f)); // R grows DOWN
            }
        }

        DrawLine(new Vector2(StripX, cy), new Vector2(StripX + StripW, cy), new Color(1, 1, 1, 0.35f)); // centre
        float nowX = StripX + StripW;
        DrawLine(new Vector2(nowX, StripY), new Vector2(nowX, StripY + StripH), new Color(1, 1, 1, 0.4f)); // "now"

        DrawString(font, new Vector2(StripX + 10f, StripY + 24f), "downstroke cell",
            HorizontalAlignment.Left, -1, 20, new Color(1f, 0.5f, 1f, 0.85f));
        DrawString(font, new Vector2(StripX + 10f, StripY + StripH - 10f), "upstroke cell",
            HorizontalAlignment.Left, -1, 20, new Color(0.4f, 0.9f, 1f, 0.9f));
    }

    // The live wingbeat: ONE oscillator drives BOTH wings, so they flap together (in phase). When
    // the downstroke cell (magenta) leads, the wings swing DOWN; when the upstroke cell (cyan)
    // leads, they swing UP. This is the honest mapping of a half-centre to a wingbeat — the two
    // sides are the up/down antagonists of one stroke, NOT the left and right wings.
    private void DrawFlappingWings(Font font)
    {
        float cx = StripX + StripW * 0.5f; // centred over the chart
        float cy = 175f; // up near the top, above the timeline (clear of the readout text)
        var hinge = new Vector2(cx, cy);

        // Stroke phase from the two cells: +1 = upstroke leading, -1 = downstroke leading.
        float phase = Mathf.Clamp((float)(_cpg.RightActivity - _cpg.LeftActivity), -1f, 1f);
        float tilt = phase * 0.7f; // radians the wings lift (up) or drop (down) from level

        const float len = 120f;
        // Both wings take the SAME tilt → they flap in phase. "-Sin" because screen-y points down.
        Vector2 leftTip = hinge + new Vector2(-Mathf.Cos(tilt), -Mathf.Sin(tilt)) * len;
        Vector2 rightTip = hinge + new Vector2(Mathf.Cos(tilt), -Mathf.Sin(tilt)) * len;

        // Colour the wings by stroke phase: magenta on the downstroke, cyan on the up.
        Color wing = new Color(1f, 0.5f, 1f).Lerp(new Color(0.3f, 0.85f, 1f), (phase + 1f) * 0.5f);

        // Faint guide showing the top and bottom of the stroke, so the swing reads as up/down.
        float reach = Mathf.Sin(0.7f) * len;
        DrawLine(new Vector2(cx - len, cy - reach), new Vector2(cx + len, cy - reach), new Color(1, 1, 1, 0.08f), 1f);
        DrawLine(new Vector2(cx - len, cy + reach), new Vector2(cx + len, cy + reach), new Color(1, 1, 1, 0.08f), 1f);

        DrawLine(hinge, leftTip, wing, 7f);
        DrawLine(hinge, rightTip, wing, 7f);
        DrawCircle(hinge, 11f, Colors.WhiteSmoke); // the fly's body between the wings

        DrawString(font, new Vector2(cx - 150f, cy + reach + 34f), "one shared beat → both wings flap in phase",
            HorizontalAlignment.Left, -1, 16, new Color(1, 1, 1, 0.6f));
    }
}
