namespace FruitFly.Living;

// A HALF-CENTRE OSCILLATOR — the smallest neural circuit that makes its OWN rhythm (Plan 0007,
// rung 1 of the flight roadmap). Two LIF neurons, L and R, on a real Network:
//   • a STEADY drive into both (a "command to fly") makes both want to fire;
//   • they INHIBIT each other, so only one wins at a time;
//   • spike-frequency ADAPTATION (fatigue) tires the winner so it hands over — forever.
// The alternation IS the beat, generated by the wiring, NOT a timer. Membrane NOISE breaks the
// opening tie (who fires first).
//
// Godot-free brain (ADR 0005): the console check and the Godot view are both just VIEWERS of this
// ONE class — neither re-wires the circuit, so there is a single source of truth.
//
// Output: LeftActivity / RightActivity — each neuron's spikes smoothed into a 0..1 signal, the
// same way the Fly turns motor spikes into muscle activation. When this drives real wings (rung 2),
// those two signals ARE the left/right wingbeat amplitude.
public sealed class HalfCentreOscillator
{
    // --- The forces that make it oscillate (the values proven in HalfCentreOscillatorCheck) ---
    private const double Inhib = 40.0; // cross-inhibition: the winner silences the loser
    private const double AdaptKick = 1.0; // fatigue per spike: how fast the winner tires (the tempo)
    private const double AdaptTau = 120.0; // ms; how slowly fatigue fades (how long a turn lasts)
    private const double Noise = 1.0; // membrane jitter: breaks the symmetric tie so SOMEONE leads

    // The "command to fly" is a real NEURON now, not an injected constant (Plan 0010). A PACEMAKER:
    // its rest sits ABOVE its own threshold, so it fires on its own with NO input — an endogenous
    // flight drive (proven in isolation by PacemakerCheck). Its spikes drive BOTH wing cells through
    // synapses, so the drive lives in the graph as a firing CAUSE you can gate or fatigue — not as a
    // number the world pushes into the effectors.
    private const double CommandRestMv = -40.0; // 10 mV above threshold ⇒ self-firing pacemaker
    private const double CommandWeight = 52.0; // command→wing synapse; sized so baseline vigour ≈ 0.204 (the
    // value LiftGain was built around) — the honest "wings sized to the body", as synapse strength

    private readonly Network _net = new();
    private readonly LifNeuron _command = new() { VRest = CommandRestMv };
    private readonly LifNeuron _l = new()
    {
        NoiseSigma = Noise,
        AdaptKick = AdaptKick,
        TauAdapt = AdaptTau,
    };
    private readonly LifNeuron _r = new()
    {
        NoiseSigma = Noise,
        AdaptKick = AdaptKick,
        TauAdapt = AdaptTau,
    };

    // Spikes smoothed into a 0..1 "how hard is this side firing" output — a leaky integral, the
    // same trick the Fly uses to turn motor spikes into a smooth muscle activation.
    private const double ActTauMs = 25.0;
    private const double ActKick = 0.12;
    private double _actL,
        _actR;

    public HalfCentreOscillator()
    {
        _net.Add(_command);
        _net.Add(_l);
        _net.Add(_r);
        _net.Connect(_command, _l, CommandWeight); // the endogenous flight drive into both wings...
        _net.Connect(_command, _r, CommandWeight); // ...equally; the L/R asymmetry comes from below
        _net.Connect(_l, _r, -Inhib); // L firing pushes R DOWN (negative weight = inhibitory)
        _net.Connect(_r, _l, -Inhib); // R firing pushes L DOWN — the mutual half of the inhibition

        // No injected baseline: the command neuron IS the drive. External input starts at 0.
    }

    // Wire a RECEPTOR into the beat: it joins this same network and synapses onto BOTH wing
    // cells with the given weight (+ = its spikes push the beat harder, − = its spikes ease it
    // off). This replaced the old SetModulation(current) hook: nothing may inject current into
    // the wing cells any more — the only way to influence the beat is a spike through a synapse.
    public void AddReceptor(LifNeuron receptor, double weight)
    {
        _net.Add(receptor);
        _net.Connect(receptor, _l, weight);
        _net.Connect(receptor, _r, weight);
    }

    // TRANSDUCTION — the one honest world→brain doorway. The body sets the current a receptor's
    // membrane feels (light, odour, motion... becoming charge is what a sense organ IS). Past the
    // receptor, only spikes through synapses move.
    public void SetReceptorInput(LifNeuron receptor, double current) =>
        _net.SetInput(receptor, current);

    // Did this receptor spike on the last tick? For viewers' gauges only — the brain itself
    // never reads this; its spikes act through their synapses above.
    public bool ReceptorFired(LifNeuron receptor) => _net.Fired(receptor);

    // Advance the circuit by one tick of dtMs and fold the new spikes into the activity outputs.
    public void Step(double dtMs)
    {
        _net.Step(dtMs); // ONE tick of the real brain — this is where the rhythm is generated
        if (_net.Fired(_l))
        {
            _actL += ActKick;
        }
        if (_net.Fired(_r))
        {
            _actR += ActKick;
        }
        _actL += (dtMs / ActTauMs) * (-_actL); // both outputs leak back toward 0 between spikes
        _actR += (dtMs / ActTauMs) * (-_actR);
    }

    // ---- Read-only state for viewers ----
    public double LeftActivity => Math.Clamp(_actL, 0.0, 1.0);
    public double RightActivity => Math.Clamp(_actR, 0.0, 1.0);
    public bool FiredLeft => _net.Fired(_l);
    public bool FiredRight => _net.Fired(_r);
}
