namespace FruitFly.Living;

// A HALF-CENTRE OSCILLATOR — the smallest neural circuit that makes its OWN rhythm (Plan 0007,
// rung 1 of the flight roadmap). Two LIF neurons, L and R, on a real Network:
//   • a STEADY drive into both (a "command to fly") makes both want to fire;
//   • they INHIBIT each other, so only one wins at a time;
//   • spike-frequency ADAPTATION (fatigue) tires the winner so it hands over — forever.
// The alternation IS the beat, generated by the wiring, NOT a timer. Membrane NOISE breaks the
// opening tie (who fires first).
//
// Godot-free brain (ADR 0005): the console check and the Godot view are both just VIEWERS of this
// ONE class — neither re-wires the circuit, so there is a single source of truth.
//
// Output: LeftActivity / RightActivity — each neuron's spikes smoothed into a 0..1 signal, the
// same way the Fly turns motor spikes into muscle activation. When this drives real wings (rung 2),
// those two signals ARE the left/right wingbeat amplitude.
public sealed class HalfCentreOscillator
{
    // --- The forces that make it oscillate (the values proven in HalfCentreOscillatorCheck) ---
    private const double Drive = 25.0; // steady "command to fly" into both cells (rheobase ~15)
    private const double Inhib = 40.0; // cross-inhibition: the winner silences the loser
    private const double AdaptKick = 1.0; // fatigue per spike: how fast the winner tires (the tempo)
    private const double AdaptTau = 120.0; // ms; how slowly fatigue fades (how long a turn lasts)
    private const double Noise = 1.0; // membrane jitter: breaks the symmetric tie so SOMEONE leads

    private readonly Network _net = new();
    private readonly LifNeuron _l = new()
    {
        NoiseSigma = Noise,
        AdaptKick = AdaptKick,
        TauAdapt = AdaptTau,
    };
    private readonly LifNeuron _r = new()
    {
        NoiseSigma = Noise,
        AdaptKick = AdaptKick,
        TauAdapt = AdaptTau,
    };

    // Spikes smoothed into a 0..1 "how hard is this side firing" output — a leaky integral, the
    // same trick the Fly uses to turn motor spikes into a smooth muscle activation.
    private const double ActTauMs = 25.0;
    private const double ActKick = 0.12;
    private double _actL,
        _actR;

    public HalfCentreOscillator()
    {
        _net.Add(_l);
        _net.Add(_r);
        _net.Connect(_l, _r, -Inhib); // L firing pushes R DOWN (negative weight = inhibitory)
        _net.Connect(_r, _l, -Inhib); // R firing pushes L DOWN — the mutual half of the inhibition

        SetCommand(Drive); // start at the default steady command
    }

    // Set the "command to fly" driving both cells. The isolation demo (Play 7) leaves it at the
    // default Drive; a reflex (Plan 0008) calls this each tick to beat HARDER or softer — more
    // command ⇒ faster firing ⇒ more vigour ⇒ more lift.
    public void SetCommand(double drive)
    {
        _net.SetInput(_l, drive);
        _net.SetInput(_r, drive);
    }

    // Advance the circuit by one tick of dtMs and fold the new spikes into the activity outputs.
    public void Step(double dtMs)
    {
        _net.Step(dtMs); // ONE tick of the real brain — this is where the rhythm is generated
        if (_net.Fired(_l))
        {
            _actL += ActKick;
        }
        if (_net.Fired(_r))
        {
            _actR += ActKick;
        }
        _actL += (dtMs / ActTauMs) * (-_actL); // both outputs leak back toward 0 between spikes
        _actR += (dtMs / ActTauMs) * (-_actR);
    }

    // ---- Read-only state for viewers ----
    public double LeftActivity => Math.Clamp(_actL, 0.0, 1.0);
    public double RightActivity => Math.Clamp(_actR, 0.0, 1.0);
    public bool FiredLeft => _net.Fired(_l);
    public bool FiredRight => _net.Fired(_r);
}
